<h1>Mais acessados</h1>

<div id="layout">
<?php
$sql = "SELECT username AS name, SUM(1) AS value FROM access_log GROUP BY username ORDER BY value DESC";

$g = new Reporter_Graph();
echo $g->Montar($sql, 'Usuários com mais acessos','user_access');
?>

<?php
$sql = "SELECT domain_of_url(`request_url`) AS name, SUM(1) AS value FROM `access_log` WHERE mime_type = 'text/html' GROUP BY name ORDER BY value DESC LIMIT 4";

$g = new Reporter_Graph();
echo $g->Montar($sql, 'Sites mais acessados','site_access');
?>
</div>
