<?php 
    $this->Grid(
                $this->oDados ,
                array(
                    'id',
                    'nome',
                    'email',
                    'celular',
                    'cidade'
                ),
                array(
                    'id' => 'lista',
                    'class' => 'tabela',
                    'cellspacing' => '1'
                )
            );
?>

