<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  
 <title>Squid Logs</title>
<?php 
#echo $this->headLink()->appendStylesheet('/css/global.css') 
echo $this->headScript(); 
echo "\n";
echo $this->headLink();
?>
</head>
<body>
<header>
<div id="user-area">
<?php
$identity = Zend_Auth::getInstance()->getIdentity();
echo "<strong>{$identity->fullname}</strong> :: ";
echo "<a href=\"/Auth/logout\">sair</a>";
?>
</div>
	<div id="header-logo">
		<b>Squid Logs</b>
	</div>
	<navigation>
	<?php echo $this->navigation()->menu()->setMaxDepth(1); ?>
	</navigation>
	
</div>
</header>
<div id="content">




<div class="breadcrumbs">
<?php
echo $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->setSeparator(" > ");
?>
</div>
 
<?php echo $this->layout()->content ?>
 
</div>
<footer>Squid Logs &copy; 2012</footer>
</body>
</html>
